version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - YOUTUBE_API_KEYS=${YOUTUBE_API_KEYS}
      - YOUTUBE_SEARCH_QUERY=${YOUTUBE_SEARCH_QUERY}
      - MONGO_URI=mongodb://mongo:27017/serri
      - PORT=3000
      - FETCH_INTERVAL=10000
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
